server.port: 8085
spring.datasource.url: jdbc:h2:file:./camunda-h2-database

engine:
  url: http://localhost:8085/engine-rest

camunda.bpm:
  admin-user:
    id: admin
    password: admin
  authorization:
    enabled: true
    authorization-check-revokes: true
    tenant-check-enabled: true
  oauth2:
    identity-provider:
      group-name-attribute: grupos
keycloak:
  url: http://localhost:8080/admin/realms

