server.port: 8085
spring.datasource.url: jdbc:h2:file:./camunda-h2-database

engine:
  url: http://localhost:8085/engine-rest

camunda.bpm:
  admin-user:
    id: admin
    password: admin
  authorization:
    enabled: true
    authorization-check-revokes: true
  oauth2:
    sso-logout:
      enabled: false
      postLogoutRedirectUri: http://localhost:8085/
    identity-provider:
      group-name-attribute: grupos
      user-name-attribute: preferred_username

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/localhost
