server.port: 8085
spring.datasource.url: jdbc:h2:file:./camunda-h2-database

engine:
  url: http://localhost:8085/engine-rest

camunda.bpm.admin-user:
  id: admin
  password: admin
camunda.bpm.authorization:
  tenant-check-enabled: true

camunda.bpm.oauth2:
  sso-logout:
    enabled: true
    postLogoutRedirectUri: http://localhost:8085/
  identity-provider:
    group-name-attribute: grupos

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/localhost  # ou o seu URI do Keycloak
          jws-key-set-uri: http://localhost:8080/realms/localhost/protocol/openid-connect/certs  # URL do JWKS do Keycloak
      client:
        registration:
          keycloak:
            client-id: localhost
            client-secret: secret
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/localhost
            user-name-attribute: preferred_username

camunda.bpm.authorization:
      enabled: true